name: eyra-rank
channels:
  - defaults
  - conda-forge
dependencies:
  - pandas=2.2.2
  - joblib=1.3.2
  - lightgbm=4.3.0
  - _openmp_mutex >=4.5
  - libgcc-ng >=12
  - libstdcxx-ng >=12
  - numpy
  - python >=3.9,<3.10.0a0
  - python_abi 3.9.* *_cp39
  - scipy

