name: eyra-rank
channels:
  - defaults
  - conda-forge
dependencies:
  - pandas=2.2.1
  - numpy=1.21.2
  - scikit-learn=1.4.1.post1
  - joblib=1.3.2
  - matplotlib=3.8.3
  - seaborn=1.11.2
  - lightgbm=3.3.1

